apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: revenue-os
  namespace: revenue-os
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: revenue-os.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: revenue-os
                port:
                  number: 80
